root_dir: /data/ruijiezzz/dataset/coloradar
output_dir: /data/ruijiezzz/dataset/processed_coloradar
voxel_output_dir: /storage/dataset/zrj/coloradar_voxel_cache
# voxel_output_dir: /storage/dataset/zrj/coloradar_voxel
num_workers: 10
single_chip_mode:
  lidar:
    FOV:
      max_range: 15.863025538680999
      az_range: [-90, 90]
      el_range: [-20, 20]
    
    ###### voxel mode #######
    # pc_range: [0, -15, -5, 15, 15, 5]
    # voxel_size: [0.05, 0.05, 0.05]
    ###### voxel mode end #######

    ###### view cone mode #######
    pc_range: [0, -90, -20, 15.8, 90, 20] # [-r, -az, -el, r, az, el], az and el are in degrees
    voxel_size: [0.05, 0.25, 0.5]  # [r, az, el], in meters and degrees, [316, 720, 80] max
    ###### view cone mode #######

    voxel_max_num_points: 10
    max_voxels: 50000



  radar:
    num_range_bins: 128
    range_bin_width: 0.124905712903
    config: /home/user/Projects/bixinzeng/RadarAR/dataset_preprocessor/config/1843_coloradar.yml
    antenna_file_path: /home/user/Projects/bixinzeng/RadarAR/dataset_preprocessor/config/antenna_array.txt
